Repository B4lage/SFM-Projekt, pull requests merged in 2021-04, with the labels that each got.

#18 gui_update_01
  version1.1.2/src/main/resources/fxml/DefaultPage.fxml
  version1.1.2/target/Javaefix-1.0-SNAPSHOT.jar
  version1.1.2/target/classes/fxml/DefaultPage.fxml
  version1.1.2/target/maven-archiver/pom.properties
  version1.1.2/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: enhancement

#25 Join day and meal table
  version1.2.1/src/main/java/hu/unideb/inf/controller/AddMealController.java
  version1.2.1/src/main/java/hu/unideb/inf/model/Day.java
  version1.2.1/src/main/java/hu/unideb/inf/model/Meal.java
Labels: database, enhancement

#29 defaultPageController szerkesztese
  version1.2.1/src/main/java/hu/unideb/inf/controller/AddMealController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/DataInController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/DefaultPageController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/LoginController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/MealsController.java
  version1.2.1/src/main/java/hu/unideb/inf/model/Day.java
  version1.2.1/src/main/java/hu/unideb/inf/model/JpaUserAuthenticationDao.java
  version1.2.1/src/main/java/hu/unideb/inf/model/Meal.java
  version1.2.1/src/main/resources/fxml/Meals.fxml
  version1.2.1/target/Javaefix-1.0-SNAPSHOT.jar
  version1.2.1/target/classes/fxml/Meals.fxml
  version1.2.1/target/classes/hu/unideb/inf/controller/AddMealController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/CreateNewMealController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/DataInController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/DefaultPageController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/LoginController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/MealsController.class
  version1.2.1/target/classes/hu/unideb/inf/model/Day.class
  version1.2.1/target/classes/hu/unideb/inf/model/JpaUserAuthenticationDao.class
  version1.2.1/target/classes/hu/unideb/inf/model/Meal.class
  version1.2.1/target/maven-archiver/pom.properties
  version1.2.1/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  version1.2.1/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: General, enhancement

#31 day tabla lekerdezesek
  version1.2.1/src/main/java/hu/unideb/inf/controller/AddMealController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/MealsController.java
  version1.2.1/src/main/resources/fxml/DataShow.fxml
  version1.2.1/src/main/resources/fxml/Login.fxml
  version1.2.1/src/main/resources/fxml/Meals.fxml
Labels: Database, enhancement
