Repository B4lage/SFM-Projekt, pull requests merged in 2021-05, with the labels that each got.

#33 0510 majorfix
  version1.2.1/src/main/java/hu/unideb/inf/MainApp.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/AddMealController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/CreateNewMealController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/DataInController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/DataShowController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/DefaultPageController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/MainPageController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/MealsController.java
  version1.2.1/src/main/java/hu/unideb/inf/model/JpaUserDao.java
  version1.2.1/src/main/java/hu/unideb/inf/model/User.java
  version1.2.1/src/main/java/hu/unideb/inf/model/UserDao.java
  version1.2.1/src/main/resources/fxml/DataIn.fxml
  version1.2.1/src/main/resources/fxml/DataShow.fxml
  version1.2.1/target/Javaefix-1.0-SNAPSHOT.jar
  version1.2.1/target/classes/fxml/DataIn.fxml
  version1.2.1/target/classes/fxml/DataShow.fxml
  version1.2.1/target/classes/fxml/Login.fxml
  version1.2.1/target/classes/fxml/Meals.fxml
  version1.2.1/target/classes/hu/unideb/inf/MainApp.class
  version1.2.1/target/classes/hu/unideb/inf/controller/AddMealController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/CreateNewMealController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/DataInController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/DataShowController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/DefaultPageController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/LoginController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/MainPageController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/MealsController.class
  version1.2.1/target/classes/hu/unideb/inf/model/JpaUserDao.class
  version1.2.1/target/classes/hu/unideb/inf/model/User.class
  version1.2.1/target/classes/hu/unideb/inf/model/UserDao.class
  version1.2.1/target/maven-archiver/pom.properties
  version1.2.1/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: General, enhancement

#37 valtozasok
  version1.2.1/nbproject/project.properties
  version1.2.1/src/main/java/hu/unideb/inf/MainApp.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/AddMealController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/CreateNewMealController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/DataInController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/DataShowController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/DefaultPageController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/LeirasController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/LoginController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/MealsController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/RegistrationController.java
  version1.2.1/src/main/java/hu/unideb/inf/model/User.java
  version1.2.1/src/main/resources/fxml/AddMeal.fxml
  version1.2.1/src/main/resources/fxml/CreateNewMeal.fxml
  version1.2.1/src/main/resources/fxml/DataIn.fxml
  version1.2.1/src/main/resources/fxml/DataShow.fxml
  version1.2.1/src/main/resources/fxml/DefaultPage.fxml
  version1.2.1/src/main/resources/fxml/Leiras.fxml
  version1.2.1/src/main/resources/fxml/Login.fxml
  version1.2.1/src/main/resources/fxml/Meals.fxml
  version1.2.1/src/main/resources/fxml/Registration.fxml
  version1.2.1/src/main/resources/fxml/application.css
  version1.2.1/target/Javaefix-1.0-SNAPSHOT.jar
  version1.2.1/target/classes/fxml/AddMeal.fxml
  version1.2.1/target/classes/fxml/CreateNewMeal.fxml
  version1.2.1/target/classes/fxml/DataIn.fxml
  version1.2.1/target/classes/fxml/DataShow.fxml
  version1.2.1/target/classes/fxml/DefaultPage.fxml
  version1.2.1/target/classes/fxml/Leiras.fxml
  version1.2.1/target/classes/fxml/Login.fxml
  version1.2.1/target/classes/fxml/Meals.fxml
  version1.2.1/target/classes/fxml/Registration.fxml
  version1.2.1/target/classes/fxml/application.css
  version1.2.1/target/classes/hu/unideb/inf/MainApp.class
  version1.2.1/target/classes/hu/unideb/inf/controller/AddMealController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/CreateNewMealController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/DataInController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/DataShowController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/DefaultPageController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/LeirasController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/LoginController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/MealsController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/RegistrationController.class
  version1.2.1/target/classes/hu/unideb/inf/model/User.class
  version1.2.1/target/maven-archiver/pom.properties
  version1.2.1/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  version1.2.1/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: General, enhancement

#38 hotfix
  version1.2.1/src/main/java/hu/unideb/inf/MainApp.java
  version1.2.1/src/main/java/hu/unideb/inf/application.css
  version1.2.1/src/main/java/hu/unideb/inf/controller/RegistrationController.java
  version1.2.1/src/main/resources/fxml/AddMeal.fxml
  version1.2.1/src/main/resources/fxml/DataIn.fxml
  version1.2.1/target/Javaefix-1.0-SNAPSHOT.jar
  version1.2.1/target/classes/fxml/AddMeal.fxml
  version1.2.1/target/classes/fxml/DataIn.fxml
  version1.2.1/target/classes/hu/unideb/inf/controller/RegistrationController.class
  version1.2.1/target/classes/hu/unideb/inf/model/ActualMeal.class
  version1.2.1/target/maven-archiver/pom.properties
  version1.2.1/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  version1.2.1/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
Labels: General, enhancement

#39 Day es Meal osztalyok tesztelese
  version1.2.1/pom.xml
  version1.2.1/src/main/java/hu/unideb/inf/model/Day.java
  version1.2.1/src/test/java/hu/unideb/inf/model/DayTest.java
  version1.2.1/src/test/java/hu/unideb/inf/model/MealTest.java
  version1.2.1/target/Javaefix-1.0-SNAPSHOT.jar
  version1.2.1/target/classes/hu/unideb/inf/MainApp.class
  version1.2.1/target/classes/hu/unideb/inf/model/Day.class
  version1.2.1/target/maven-archiver/pom.properties
  version1.2.1/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  version1.2.1/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  version1.2.1/target/surefire-reports/TEST-hu.unideb.inf.model.DayTest.xml
  version1.2.1/target/surefire-reports/TEST-hu.unideb.inf.model.MealTest.xml
  version1.2.1/target/surefire-reports/hu.unideb.inf.model.DayTest.txt
  version1.2.1/target/surefire-reports/hu.unideb.inf.model.MealTest.txt
  version1.2.1/target/test-classes/hu/unideb/inf/model/DayTest.class
  version1.2.1/target/test-classes/hu/unideb/inf/model/MealTest.class
Labels: JUnit, enhancement

#41 szeretlek
  version1.2.1/src/main/java/hu/unideb/inf/controller/AddMealController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/CreateNewMealController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/DataInController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/DataShowController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/DefaultPageController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/LeirasController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/LoginController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/MealsController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/RegistrationController.java
  version1.2.1/src/main/resources/fxml/106-1065648_healthy-food-png-image-with-transparent-background-healthy.png
  version1.2.1/src/main/resources/fxml/AddMeal.fxml
  version1.2.1/src/main/resources/fxml/CreateNewMeal.fxml
  version1.2.1/src/main/resources/fxml/DataIn.fxml
  version1.2.1/src/main/resources/fxml/DataShow.fxml
  version1.2.1/src/main/resources/fxml/DefaultPage.fxml
  version1.2.1/src/main/resources/fxml/Leiras.fxml
  version1.2.1/src/main/resources/fxml/Login.fxml
  version1.2.1/src/main/resources/fxml/Meals.fxml
  version1.2.1/src/main/resources/fxml/Registration.fxml
  version1.2.1/src/main/resources/fxml/application.css
  version1.2.1/src/main/resources/fxml/monke.png
  version1.2.1/src/test/java/hu/unideb/inf/model/DayTest.java
  version1.2.1/target/Javaefix-1.0-SNAPSHOT.jar
  version1.2.1/target/classes/fxml/106-1065648_healthy-food-png-image-with-transparent-background-healthy.png
  version1.2.1/target/classes/fxml/AddMeal.fxml
  version1.2.1/target/classes/fxml/CreateNewMeal.fxml
  version1.2.1/target/classes/fxml/DataIn.fxml
  version1.2.1/target/classes/fxml/DataShow.fxml
  version1.2.1/target/classes/fxml/DefaultPage.fxml
  version1.2.1/target/classes/fxml/Leiras.fxml
  version1.2.1/target/classes/fxml/Login.fxml
  version1.2.1/target/classes/fxml/Meals.fxml
  version1.2.1/target/classes/fxml/Registration.fxml
  version1.2.1/target/classes/fxml/application.css
  version1.2.1/target/classes/fxml/monke.png
  version1.2.1/target/classes/hu/unideb/inf/controller/AddMealController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/CreateNewMealController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/DataInController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/DataShowController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/DefaultPageController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/LeirasController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/LoginController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/MealsController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/RegistrationController.class
  version1.2.1/target/maven-archiver/pom.properties
  version1.2.1/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  version1.2.1/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  version1.2.1/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  version1.2.1/target/surefire-reports/TEST-hu.unideb.inf.model.DayTest.xml
  version1.2.1/target/surefire-reports/TEST-hu.unideb.inf.model.MealTest.xml
  version1.2.1/target/surefire-reports/hu.unideb.inf.model.DayTest.txt
  version1.2.1/target/surefire-reports/hu.unideb.inf.model.MealTest.txt
  version1.2.1/target/test-classes/hu/unideb/inf/model/DayTest.class
Labels: GUI

#45 TableView Style
  version1.2.1/src/main/resources/fxml/AddMeal.fxml
  version1.2.1/src/main/resources/fxml/Meals.fxml
  version1.2.1/src/main/resources/fxml/application.css
  version1.2.1/target/Javaefix-1.0-SNAPSHOT.jar
  version1.2.1/target/classes/fxml/AddMeal.fxml
  version1.2.1/target/classes/fxml/Meals.fxml
  version1.2.1/target/classes/fxml/application.css
  version1.2.1/target/maven-archiver/pom.properties
  version1.2.1/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  version1.2.1/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  version1.2.1/target/surefire-reports/TEST-hu.unideb.inf.model.DayTest.xml
  version1.2.1/target/surefire-reports/TEST-hu.unideb.inf.model.MealTest.xml
  version1.2.1/target/surefire-reports/TEST-hu.unideb.inf.model.UserAuthenticationTest.xml
  version1.2.1/target/surefire-reports/TEST-hu.unideb.inf.model.UserTest.xml
  version1.2.1/target/surefire-reports/hu.unideb.inf.model.DayTest.txt
  version1.2.1/target/surefire-reports/hu.unideb.inf.model.MealTest.txt
  version1.2.1/target/surefire-reports/hu.unideb.inf.model.UserAuthenticationTest.txt
  version1.2.1/target/surefire-reports/hu.unideb.inf.model.UserTest.txt
Labels: GUI, enhancement

#47 Alert Style
  version1.2.1/src/main/java/hu/unideb/inf/controller/AddMealController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/CreateNewMealController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/DataInController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/DefaultPageController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/LoginController.java
  version1.2.1/src/main/java/hu/unideb/inf/controller/RegistrationController.java
  version1.2.1/src/main/resources/fxml/application.css
  version1.2.1/src/main/resources/fxml/dialog.css
  version1.2.1/src/main/resources/fxml/icon.png
  version1.2.1/target/Javaefix-1.0-SNAPSHOT.jar
  version1.2.1/target/classes/fxml/application.css
  version1.2.1/target/classes/fxml/dialog.css
  version1.2.1/target/classes/fxml/icon.png
  version1.2.1/target/classes/hu/unideb/inf/controller/AddMealController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/CreateNewMealController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/DataInController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/DefaultPageController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/LoginController.class
  version1.2.1/target/classes/hu/unideb/inf/controller/RegistrationController.class
  version1.2.1/target/maven-archiver/pom.properties
  version1.2.1/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  version1.2.1/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  version1.2.1/target/surefire-reports/TEST-hu.unideb.inf.model.DayTest.xml
  version1.2.1/target/surefire-reports/TEST-hu.unideb.inf.model.MealTest.xml
  version1.2.1/target/surefire-reports/TEST-hu.unideb.inf.model.UserAuthenticationTest.xml
  version1.2.1/target/surefire-reports/TEST-hu.unideb.inf.model.UserTest.xml
  version1.2.1/target/surefire-reports/hu.unideb.inf.model.DayTest.txt
  version1.2.1/target/surefire-reports/hu.unideb.inf.model.UserAuthenticationTest.txt
Labels: GUI, enhancement

#48 GUI
  version1.2.1/src/main/resources/fxml/AddMeal.fxml
  version1.2.1/src/main/resources/fxml/CreateNewMeal.fxml
  version1.2.1/src/main/resources/fxml/DataIn.fxml
  version1.2.1/src/main/resources/fxml/DataShow.fxml
  version1.2.1/src/main/resources/fxml/DefaultPage.fxml
  version1.2.1/src/main/resources/fxml/Leiras.fxml
  version1.2.1/src/main/resources/fxml/Login.fxml
  version1.2.1/src/main/resources/fxml/MainPage.fxml
  version1.2.1/src/main/resources/fxml/Meals.fxml
  version1.2.1/src/main/resources/fxml/Registration.fxml
Labels: GUI, enhancement
